from __future__ import annotations

LEGACY_FORWARD_ALGORITHM_VERSION = "paper_forward_v2"
Q1_ALGORITHM_VERSION = "q1_math_core_v1"
SUPPORTED_PAPER_ALGORITHM_VERSIONS = (
    LEGACY_FORWARD_ALGORITHM_VERSION,
    Q1_ALGORITHM_VERSION,
)
